name: CI - Build and Test

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ develop ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./backend/SoftBarter.API

    - name: Build application
      run: dotnet build --no-restore --configuration Release
      working-directory: ./backend/SoftBarter.API

    - name: Run tests
      run: dotnet test --no-build --configuration Release --verbosity normal
      working-directory: ./backend/SoftBarter.API

  test-web:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: ./web

    - name: Run tests
      run: npm test -- --coverage --watchAll=false
      working-directory: ./web

    - name: Build application
      run: npm run build
      working-directory: ./web
      env:
        REACT_APP_API_URL: http://localhost:5032

  test-mobile:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: mobile/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: ./mobile

    - name: Run TypeScript check
      run: npx tsc --noEmit
      working-directory: ./mobile

    - name: Test build
      run: npx expo export --platform web
      working-directory: ./mobile