name: Build and Deploy Mobile App

on:
  push:
    branches: [ main ]
    paths: [ 'mobile/**' ]
  workflow_dispatch:

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: mobile/package-lock.json

    - name: Setup Expo CLI
      run: npm install -g @expo/cli

    - name: Install dependencies
      run: npm ci
      working-directory: ./mobile

    - name: Build for Android
      run: npx expo build:android --type apk
      working-directory: ./mobile
      if: github.ref == 'refs/heads/main'

    - name: Build for iOS
      run: npx expo build:ios --type archive
      working-directory: ./mobile
      if: github.ref == 'refs/heads/main'

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: mobile/*.apk
      if: github.ref == 'refs/heads/main'

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: mobile/package-lock.json

    - name: Setup Expo CLI
      run: npm install -g @expo/cli

    - name: Install dependencies
      run: npm ci
      working-directory: ./mobile

    - name: Publish to Expo
      run: npx expo publish --non-interactive
      working-directory: ./mobile
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: mobile-v${{ github.run_number }}
        release_name: Mobile App Release v${{ github.run_number }}
        body: |
          Mobile app build ${{ github.run_number }}
          
          ## Download Options
          - Install Expo Go app and scan QR code
          - Download APK from artifacts (Android)
          
          ## Changes
          - See commit history for detailed changes
        draft: false
        prerelease: false