name: Deploy Backend to Azure App Service

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: softbarter-api
  AZURE_WEBAPP_PACKAGE_PATH: './backend/SoftBarter.API'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Build application
      run: dotnet build --no-restore --configuration Release
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Run tests
      run: dotnet test --no-build --configuration Release --verbosity normal
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      continue-on-error: true

    - name: Publish application
      run: dotnet publish --no-build --configuration Release --output ./publish
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish

    - name: Health Check
      run: |
        sleep 30
        curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/health || exit 1