name: Build and deploy ASP.Net Core app to Azure Web App - softbarter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: List repo contents
        run: Get-ChildItem -Recurse

      # Build React frontend (update path if your ClientApp is elsewhere)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: backend/SoftBarter.API/ClientApp
        run: npm ci

      - name: Build frontend
        working-directory: backend/SoftBarter.API/ClientApp
        run: npm run build

      # Copy React build output to wwwroot
      - name: Copy frontend build to wwwroot
        run: |
          if (Test-Path "backend/SoftBarter.API/wwwroot") {
            Remove-Item -Recurse -Force "backend/SoftBarter.API/wwwroot"
          }
          Copy-Item -Path "backend/SoftBarter.API/ClientApp/build" -Destination "backend/SoftBarter.API/wwwroot" -Recurse -Force

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release backend/SoftBarter.API/SoftBarter.API.csproj

      - name: dotnet publish
        run: dotnet publish backend/SoftBarter.API/SoftBarter.API.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'softbarter'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DE137D58D0634989ABD5415C904FC270 }}
