name: Build and deploy ASP.Net Core app to Azure Web App - softbarter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Build React frontend
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # Clean wwwroot and copy frontend build output
      - name: Remove old wwwroot (if exists)
        run: |
          if (Test-Path "backend/SoftBarter.API/wwwroot") {
            Remove-Item -Recurse -Force "backend/SoftBarter.API/wwwroot"
          }

      - name: Create wwwroot
        run: New-Item -ItemType Directory -Path "backend/SoftBarter.API/wwwroot"

      - name: Copy frontend build to wwwroot
        run: Copy-Item -Path "frontend/build/*" -Destination "backend/SoftBarter.API/wwwroot" -Recurse

      # Build and publish backend
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release backend/SoftBarter.API/SoftBarter.API.csproj

      - name: dotnet publish
        run: dotnet publish backend/SoftBarter.API/SoftBarter.API.csproj -c Release -o published_app

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: published_app

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'softbarter'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DE137D58D0634989ABD5415C904FC270 }}
